apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: drjmcc
    provider: github
    repository: jenkinsx-test
  name: drjmcc-jenkinsx-test
spec:
  description: Imported application for drjmcc/jenkinsx-test
  httpCloneURL: https://github.com/drjmcc/jenkinsx-test.git
  org: drjmcc
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: jenkinsx-test
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/drjmcc/jenkinsx-test.git
